stages:
  prepare:
    matrix:
      path: ${path}
    cmd: >-
      python prepare_benchmarking.py --path ${item.path}
  train:
    matrix:
      base_classifier: ${base_classifiers}
      model: ${models}
      random_state: ${random_states}
      train_split: ${train_splits}
      cal_split: ${cal_splits}
      n_jobs: ${n_jobs}
      path: ${path}
      noise: ${noises}
    cmd: >-
      /usr/bin/time -v
      python train.py
      --base_classifier ${item.base_classifier}
      --model ${item.model}
      --n_jobs ${item.n_jobs}
      --random_state ${item.random_state}
      --train_split ${item.train_split}
      --cal_split ${item.cal_split}
      --path ${item.path}
      --noise ${item.noise}
      2>> ${item.path}results/benchmark/memory/train/train_${item.model}_${item.base_classifier}_${item.random_state}.txt
    deps:
      - data/platypus_diseases.csv
  calibrate:
    matrix:
      base_classifier: ${base_classifiers}
      model: ${models}
      calibration_method: ${calibration_methods}
      random_state: ${random_states}
      train_split: ${train_splits}
      cal_split: ${cal_splits}
      n_jobs: ${n_jobs}
      path: ${path}
      noise: ${noises}
    cmd: >-
      /usr/bin/time -v
      python calibrate.py
      --base_classifier ${item.base_classifier}
      --model ${item.model}
      --calibration_method ${item.calibration_method}
      --n_jobs ${item.n_jobs}
      --random_state ${item.random_state}
      --train_split ${item.train_split}
      --cal_split ${item.cal_split}
      --path ${item.path}
      --noise ${item.noise}
      2>> ${item.path}results/benchmark/memory/calibration/calibrate_${item.model}_${item.base_classifier}_${item.calibration_method}_${item.random_state}.txt
    deps:
    - data/platypus_diseases.csv
  calibrate_cleanup:
    matrix:
      path: ${path}
    cmd: rm -R ${item.path}results/train/
  evaluate:
    matrix:
      base_classifier: ${base_classifiers}
      model: ${models}
      calibration_method: ${calibration_methods}
      random_state: ${random_states}
      train_split: ${train_splits}
      cal_split: ${cal_splits}
      path: ${path}
      noise: ${noises}
    cmd: >-
      /usr/bin/time -v
      python evaluate.py
      --base_classifier ${item.base_classifier}
      --model ${item.model}
      --calibration_method ${item.calibration_method}
      --random_state ${item.random_state}
      --train_split ${item.train_split}
      --cal_split ${item.cal_split}
      --path ${item.path}
      --noise ${item.noise}
      2>> ${item.path}results/benchmark/memory/evaluation/evaluate_${item.model}_${item.base_classifier}_${item.calibration_method}_${item.random_state}.txt
    deps:
    - data/platypus_diseases.csv
  evaluate_cleanup:
    matrix:
      path: ${path}
    cmd: rm -R ${item.path}results/calibration/